### ISSUE TITLE
请问IOSAppDelegate(WeChatExt)中的方法是在程序中被生命周期自动调用吗？

### ISSUE THREAD

**Issue by Robortz** [tkzcfc/WeiXinSDK#1]
感谢你的贡献，给我们这种刚接触UE4的人提供了很大的帮助。个人尝试了代码以后发现了一个问题，我是以直接放在程序中Thirdparty形式接入的（非插件）发现IOSAppDelegate(WeChatExt)中的方法没有被自动调用，想问一下是否有其他地方要进行相关设定。感谢作者！

**Comment by tkzcfc** [comment]
你好，很荣幸这个项目能帮到你。关于你说的这个问题我并没有在使用中发现。我也是个刚接触UE4的新手，所有我不知道以Thirdparty形式接入和插件接入有何区别，我怀疑是object-c的代码没有编译进去。你能告诉我现在能不能跳转到微信的APP里面吗？

**Comment by Robortz** [comment]
区别可能还是有一点的，我目前是能成功跳转，学着你的代码加了一个IOSAppDelegate(WeChatExt)类，但是不知道怎么设置让这个类绑定到app的生命周期上去，所以也没法成功回调了

**Comment by tkzcfc** [comment]
不好意思 现在才回复 现在你分享成功后返回APP时 回调并没有进入到-(void)onResp:(BaseResp*)resp函数中吗？  你可以打印一个日志查看一下 如果进入了 那表明分享回调确实是返回了

**Comment by Robortz** [comment]
你的方法我验证成功了，是我自己这边之前有些问题。很感谢你的分享和帮主

**Comment by kaioser** [comment]
@tkzcfc @Robortz 两位您好，想请教两位一个问题，我用objective-c写了一个轻量级的静态库，就是两个页面A和B之间跳转的。把这个库导入到UE4里之后，应该如何进入我这个库的页面A里呢？打扰两位了，感激不尽！
