### ISSUE TITLE
将该插件拷贝至工程目录下的Plugins文件夹中无法编译

### ISSUE THREAD

**Issue by jacklsl** [tkzcfc/WeiXinSDK#2]
很感谢你能提供这类插件，但当我将该插件拷贝至工程目录下的Plugins文件夹中无法编译。我是使用的时UE4.19.1版本，将WeiXinSDK模块添加到ShareImage.Build.cs中编译出现下面的错误：

错误	Unreal Projects\ShareImage\Plugins\WeiXinSDK\Source\WeiXinSDK\WeiXinSDK.Build.cs(94,75) : error CS0122: “UnrealBuildTool.BuildConfiguration”不可访问，因为它受保护级别限制。

请问这是什么原因造成的？

**Comment by tkzcfc** [comment]
你好 可能是虚幻版本的问题 我使用4.17开发的 在家我试了下4.19的版本重现了你说的问题

你可以先暂时把WeiXinSDK.Build.cs中的92行改成
            //string PluginPath = Utils.MakePathRelativeTo(ModuleDirectory, BuildConfiguration.RelativeEnginePath);
            AdditionalPropertiesForReceipt.Add(new ReceiptProperty("AndroidPlugin", Path.Combine(ModuleDirectory, "WeiXinSDK_APL.xml")));
家里没有安装安卓的编译环境，待会儿去公司我在验证这样是否可行

**Comment by jacklsl** [comment]
验证过后，希望能告诉我结果，谢谢！

**Comment by tkzcfc** [comment]
试了下 可以的

**Comment by jacklsl** [comment]
AdditionalPropertiesForReceipt.Add(new ReceiptProperty("AndroidPlugin", Path.Combine(ModuleDirectory, "WeiXinSDK_APL.xml"))); 这个不需要注释掉吗？，如果不注释掉 还是无法编译

**Comment by tkzcfc** [comment]
这句话不需要注释掉 现在报的什么错？

**Comment by jacklsl** [comment]
![qq 20180711153043](https://user-images.githubusercontent.com/10347554/42556848-828d15ba-851f-11e8-926c-813448aa8cac.png)

**Comment by tkzcfc** [comment]
把你的代码截图给我看看

**Comment by jacklsl** [comment]
![qq 20180711153329](https://user-images.githubusercontent.com/10347554/42556964-cc8c2c8c-851f-11e8-9a78-b036803a2a6b.png)

**Comment by tkzcfc** [comment]
AdditionalPropertiesForReceipt.Add(new ReceiptProperty("AndroidPlugin", Path.Combine(ModuleDirectory, "WeiXinSDK_APL.xml")));
改成这样 你没看第二句代码吧。。。

**Comment by jacklsl** [comment]
不好意思，大眼一看以为跟原来的没区别呢

**Comment by tkzcfc** [comment]
好吧

**Comment by jacklsl** [comment]
打安卓包的时候出错，这是什么原因？
![qq 20180711160211](https://user-images.githubusercontent.com/10347554/42558495-0003122a-8524-11e8-8c2a-9c7e4fbfa35d.png)
![qq 20180711160247](https://user-images.githubusercontent.com/10347554/42558501-0355ba9a-8524-11e8-955d-6a424dc53e33.png)

**Comment by tkzcfc** [comment]
将Source/WeiXinSDK/WeiXinSDK_APL.xml中的包名com.ChengduWonderVision.BlockMaster替换成自己的包名

**Comment by jacklsl** [comment]
好的，谢谢

**Comment by jacklsl** [comment]
打完安卓包后，使用分享文字功能，无法调出微信

**Comment by Robortz** [comment]
检查一下手机是否装载新版本微信，检查你目前使用的微信id和包名及签名是否和在微信后台申请的一致，如果都没问题在调用的地方下log看一下没有调出的原因！

**Comment by jacklsl** [comment]
好的，谢谢
