### ISSUE TITLE
Freelance work opportunity in China

### ISSUE THREAD

**Issue by hulpesergiu** [tkzcfc/WeiXinSDK#6]
Hi, I'm working on a small iOS project for a company in China, and I want to pay you to update this plugin to UE4.26.

Let me know if you are interested, you can add me on WeChat, my ID is: sergiuh

**Comment by tkzcfc** [comment]
Sorry, I don't have a MacOS environment now. You can try to copy the code. If there is an error, I can help you solve it

**Comment by he1016060110** [comment]
哥们有没有适配ue5的新版本，你这个很有用，可惜没有更新

**Comment by tkzcfc** [comment]
没有  我现在工作没用ue了  你看下ue5的插件规范  把这些代码考过去就行了  代码量也不大
