### ISSUE TITLE
UnReal 5.3 

### ISSUE THREAD

**Issue by Lambert-Huang** [tkzcfc/WeiXinSDK#7]
老哥，打扰一下，我把这个插件拖到 UE 工程中之后报错找不到 WXApi.h 中的接口，你有碰到过吗？万分感谢

**Comment by tkzcfc** [comment]
这个插件的引擎版本是4.2的 5.x版本的要升级下  将头文件目录加到工程中 [WeiXinSDK.Build.cs](https://github.com/tkzcfc/WeiXinSDK/blob/master/Source/WeiXinSDK/WeiXinSDK.Build.cs#L68)

**Comment by Lambert-Huang** [comment]
太感谢了，我这样添加可以吗？
PublicIncludePaths.Add(Path.Combine(ModuleDirectory, "..", "ThirdParty", "IOS"));
报错信息是这样的：
/Users/lambert/Documents/Unreal Projects/XinDongUE/XDDemo/Plugins/WeiXinSDK/Source/WeiXinSDK/Private/WeiXinSDKFunctions.cpp:104:9: error: class method '+registerApp:' not found (return type defaults to 'id') [-Werror,-Wobjc-method-access]
LogPlayLevel: UAT:         [WXApi registerApp : @"wxbb08167f21b361a2"];

**Comment by tkzcfc** [comment]
这个报错是因为微信的SDK没有加到工程中 导致方法找不到  你最好按照微信官方教程来接  我这个SDK版本和引擎版本都过时了

**Comment by Lambert-Huang** [comment]
> 这个报错是因为微信的SDK没有加到工程中 导致方法找不到 你最好按照微信官方教程来接 我这个SDK版本和引擎版本都过时了

好的，谢谢大佬，我去看看微信官方和 ue 对接的文档
